// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnvCY_v_7i5Gtp9KG-V7VBwPVqUYAoXmI',
    appId: '1:1084701083452:web:7c0793cd1c35ff01ef4039',
    messagingSenderId: '1084701083452',
    projectId: 'billing-c4c26',
    authDomain: 'billing-c4c26.firebaseapp.com',
    storageBucket: 'billing-c4c26.firebasestorage.app',
    measurementId: 'G-7D0KX7H302',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-FFiHS-mTYYIaxn2_wJEsM9aL4sCpfi0',
    appId: '1:1084701083452:android:176d4443fd090d30ef4039',
    messagingSenderId: '1084701083452',
    projectId: 'billing-c4c26',
    storageBucket: 'billing-c4c26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdLL12_lO_wO7rFIYG3ctzUSyP8BMHQPk',
    appId: '1:1084701083452:ios:edcdca7dc15ad659ef4039',
    messagingSenderId: '1084701083452',
    projectId: 'billing-c4c26',
    storageBucket: 'billing-c4c26.firebasestorage.app',
    iosBundleId: 'com.example.devkiagrobilling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdLL12_lO_wO7rFIYG3ctzUSyP8BMHQPk',
    appId: '1:1084701083452:ios:edcdca7dc15ad659ef4039',
    messagingSenderId: '1084701083452',
    projectId: 'billing-c4c26',
    storageBucket: 'billing-c4c26.firebasestorage.app',
    iosBundleId: 'com.example.devkiagrobilling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnvCY_v_7i5Gtp9KG-V7VBwPVqUYAoXmI',
    appId: '1:1084701083452:web:da15e5ef2b70044bef4039',
    messagingSenderId: '1084701083452',
    projectId: 'billing-c4c26',
    authDomain: 'billing-c4c26.firebaseapp.com',
    storageBucket: 'billing-c4c26.firebasestorage.app',
    measurementId: 'G-NL2P204LWF',
  );
}
